Pre annotation filtering
populationgenomics/tob-wgs pull request #130
Opened 2022-09-28 12:42 UTC by illusional

- Minor cleanup of `get_association_effect_data`
- Filter on computed snp_id to avoid annotating whole table + save memory
- Reorder `filter_cols` from #127 to preserve _filtering on rows with a certain variance_ (_outlier sample that has high variance, that SNP will be retained, but if you filter out that sample you’ll have a different subset of variants_) @KatalinaBobowik.

2022-09-28 21:42 UTC, lgruen requested changes

2022-09-28 21:42 UTC, lgruen commented on scripts/eqtl_hail_batch/launch_eqtl_spearman.py
>      mt = mt.persist('MEMORY_AND_DISK')
`persist` is a no-op in QoB. Did you mean to use `checkpoint`?

2022-09-28 23:26 UTC, lgruen approved these changes

2022-09-28 23:26 UTC, lgruen commented on scripts/eqtl_hail_batch/launch_eqtl_spearman.py
> +        output_path(f'eqtl/{cell_type}/{chromosome}/{gene_name}.mt', 'tmp'),
```suggestion
        output_path(f'eqtl/{cell_type}/{chromosome}/{gene_name}/spearman_correlation_scatter_filter.mt', 'tmp'),
```

2022-09-29 00:32 UTC, KatalinaBobowik approved these changes
👍

2022-09-29 00:40 UTC, merged